### ISSUE TITLE
Participant issue list

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/friendly-github-intro#3]
When you're completing the [My first repo](https://kirstiejane.github.io/friendly-github-intro/exercises/my-first-repo/) exercise you might want to try submitting a change to another person's repository or asking someone to submit a pull request to your own.

Comment on this issue with a **link to the issue** in your repository to ask workshop participants to help you out.

**Comment by smithcg02** [comment]
Here's a link to a test issue I've just created;
https://github.com/smithcg02/TESTtest/issues/3
I merely need your name and your favourite breed of dog :)
Thanks
Chris
