### ISSUE TITLE
Participant Issue List

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/friendly-github-intro#37]
Add a comment to this issue linking to an issue that you've created for your project.
For example:

> Hi, I'm [Kirstie](https://github.com/KirstieJane) and I'm looking for help with my [Open Advice](https://github.com/KirstieJane/OpenAdvice) project. In particular, [this issue](https://github.com/KirstieJane/OpenAdvice/issues/1) asks for common questions that people who want to start working more openly may have. Please come along and contribute if you can!

**Comment by SuperKam91** [comment]
Can people add food to the list in the readme file? I have created the relevant issue.
https://github.com/SuperKam91/first_repos/issues/4
https://github.com/SuperKam91/first_repos

**Comment by smc204** [comment]
Hi, I'm trying this out - can you check out my issue here for my first [repo](https://github.com/smc204/friendly-collab-repo/issues/5)?

**Comment by debasishuiuc** [comment]
https://github.com/debasishuiuc/github-intro-camb 

Can someone help me find the synonym of "Extrovert" and update the README file ?

**Comment by KirstieJane** [comment]
Hey @SuperKam91 - when you linked to your repository it doesn't tell me what you want to do. You can try changing the link to your issue, eg: https://github.com/SuperKam91/first_repos/issues/4.

Same goes for your link @debasishuiuc: You could link to the issue itself rather than the repository: https://github.com/debasishuiuc/github-intro-camb/issues/1

**Comment by KirstieJane** [comment]
Great job @smc204! Excited to see that your issue is already closed!!! 🎉 😀 🍰 :beers:

**Comment by debasishuiuc** [comment]
https://github.com/debasishuiuc/github-intro-camb/issues/1

Question: Does this require people who wish to help fork first and then ask for a pull ?

**Comment by KirstieJane** [comment]
Hi @debasishuiuc - The work flow is usually to figure out what needs to happen through a discussion at your issue. Once they know what needs to happen then, yes - they'll fork and then submit a pull request!
