### ISSUE TITLE
Broken link in exercise working-locally

### ISSUE THREAD

**Issue by pajanne** [KirstieJane/friendly-github-intro#41]
Hi Kirstie,

I am not doing a pull request for this one because I don't know how you wish the display these links. They are not working:

`
<a href="#">https://help.github.com/articles/cloning-a-repository/</a>
` 

https://kirstiejane.github.io/friendly-github-intro/exercises/working-locally/
These four links do not go anywhere:
- Cloning a repository using the command line https://help.github.com/articles/cloning-a-repository/
- Add a file to a repository using the command line https://help.github.com/articles/adding-a-file-to-a-repository-using-the-command-line/
- Add an existing project to github using the command line https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/
- Video showing how to add a new repository from your laptop https://www.youtube.com/embed/u0M0HYJNvmE

**Comment by KirstieJane** [comment]
Suuuper helpful! Thank you! Fixing now....

**Comment by pajanne** [comment]
Fab! Fixed now ;)
